### ISSUE TITLE
[orgs] api proposal

### ISSUE THREAD

**Issue by maxakuru** [adobe/helix-rum-bundler#65]
- Create org (superuser only)
  - `POST /orgs -d { id: string }`
- List orgs (superuser only)
  - `GET /orgs` -> `{ orgs: string[] }`
- Get org
  - `GET /orgs/{id} -h { Authorization: Bearer {orgkey|sukey} }` -> `{ domains: string[] }`
- Add domain to org (superuser only)
  - `POST /orgs/{id} -d { domains: string[] }`
- Remove domain from org (superuser only)
  - `DELETE /orgs/{id}/domains/{domain}`
- Get orgkey
  - `GET /orgs/{id}/key -h { Authorization: Bearer {orgkey|sukey} }` -> `{ orgkey: string }`
- Rotate orgkey
  - `POST /orgs/{id}/key -h { Authorization: Bearer {orgkey|sukey} }` -> `{ orgkey: string }`
- Set orgkey (superuser only)
  - `PUT /orgs/{id}/key -d { orgkey: string }`
- Get domainkey using orgkey
  - `GET /domainkey/{domain} -h { Authorization: Bearer {orgkey} }`

**Comment by langswei** [comment]
A few questions:
1) Can a domain be part of multiple orgs?
2) What is the intent of an orgkey?  Is it to allow optionality for a future UI to allow someone with that key to either aggregate multiple domains in one screen, or drill into each domain like a folder/file model?

**Comment by davidnuescheler** [comment]
(1) yes, currently
(2) i think of it as initially allowing someone to read and set domainkeys eg. to switch between all domains of an org in rum explorer.

**Comment by langswei** [comment]
Will the holder of a domain key be able to get the containing org(s)?  If not (as per the current proposal), it seems like org key holders may need to have both the domainkey and the orgkey in the URL to be able to navigate back and forth -- perhaps something like breadcrumb navigation.

We small group of key distributors will have to be a little careful/deliberate when we deliver dashboard URLs to our customers in larger orgs -- not a problem, just an observation.

**Comment by maxakuru** [comment]
the idea is that an `orgkey` will act similarly to the `superuserkey` you currently use, so customers can set their own `orgkey` in localStorage and switch between domains they have access to

what they do with the `domainkey` scoped urls afterwards is up to them

**Comment by langswei** [comment]
Got it, thx.  So while a domain can be in multiple orgs, in general a user will be tied to one org unless they swap out the local storage key.  Makes sense.
